# Generated by Django 4.1.3 on 2023-02-28 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.datetime(2023, 3, 1, 1, 53, 54, 32114))),
                ('end_time', models.TimeField(default=datetime.datetime(2023, 3, 1, 1, 53, 54, 32114))),
                ('capacity', models.PositiveSmallIntegerField()),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('preferred_area', models.CharField(blank=True, max_length=50)),
                ('preferred_start_time', models.TimeField(blank=True, default=datetime.datetime(2023, 3, 1, 1, 53, 54, 33115))),
                ('assigned_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.shift')),
            ],
        ),
    ]
