# Generated by Django 4.1.3 on 2023-03-01 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_shift_end_time_alter_shift_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='max_capacity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 1, 11, 6, 26, 66750)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 1, 11, 6, 26, 66750)),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 3, 1, 11, 6, 26, 66750)),
        ),
    ]
