# Generated by Django 4.1.3 on 2023-03-01 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_shift_max_capacity_alter_shift_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='capacity',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 1, 11, 25, 15, 167222)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 1, 11, 25, 15, 167222)),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 3, 1, 11, 25, 15, 168222)),
        ),
    ]
